### ISSUE TITLE
Support for osx-64

### ISSUE THREAD

**Issue by Dhananjhay** [conda-forge/connectome-workbench-split-feedstock#11]
### Comment:

Hi there,

Thank you for maintaining this excellent package! I'm a developer on the [hippunfold](https://github.com/khanlab/hippunfold) project, and we've been using a custom conda package for connectome-workbench via our [khanlab channel](https://anaconda.org/khanlab/repo) ([recipe here](https://github.com/Dhananjhay/staged-recipes/blob/djay/add-dev-workbench/recipes/workbench/meta.yaml)).

We're currently working on extending hippunfold support to osx-64, and it would be incredibly helpful to know how to make connectome-workbench build available for that platform on our custom channel. Would it be possible for you give some suggestions or maybe add osx-64 support to this feedstock?

Thanks so much for your time and for all your work on this!

Best regards,
Dhananjhay

**Comment by effigies** [comment]
I am all for adding OSX support to this feedstock, I just don't have a Mac to do any testing on, and the obvious first things I tried didn't pass CI. My target is Linux Docker environments, so I dropped it in hopes that someone who needed this would come along. Hi!

If you would like to add support, I would suggest making sure that you can build connectome-workbench from source, outside the conda context entirely. Once you've gotten that down, you could move over to using [build-locally.py](https://github.com/conda-forge/connectome-workbench-split-feedstock/blob/main/build-locally.py) to see if you can debug the OSX build.

**Comment by Dhananjhay** [comment]
Hello there!

I've successfully built and compiled Connectome Workbench from source outside the conda environment, and it runs perfectly on my system. I'm on an M-series Mac (Apple Silicon), so I'm using Rosetta 2 emulation to build for the osx-64 architecture.

I was also able to build the Conda package locally using this setup. However, I’m running into issues with the test phase, specifically when running:

`wb_command -version`

Here’s a quick breakdown:

build.sh:
```
#!/usr/bin/env bash
set -euo pipefail

mkdir build
cd build


arch -x86_64 cmake $CMAKE_ARGS -GNinja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DWORKBENCH_USE_QT5=TRUE \
  -DWORKBENCH_MESA_DIR="$PREFIX" \
  ../src

arch -x86_64 ninja
arch -x86_64 ninja install
```

meta.yaml:
```
{% set name = "dev-connectome-workbench" %}
{% set version = "2.0.1" %}
{% set ref = "91217a2e51f1ea6f8c425f88c4a07dbae21be212" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://github.com/Dhananjhay/workbench/archive/{{ ref }}.tar.gz
  sha256: 92eb3db711937b22f84af2575af8c5282d09e71cfb0117555d89e2bd21ea7f28

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    # - {{ stdlib('c') }}
    - cmake >=3.0  # [linux]
    - cmake >=3.5  # [osx]
    - ninja
    - qwt
    # OpenMP
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    # libGL
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
  host:
    - qt
    - openssl
    # 1.2 is ABI compatible with 1.3, so this provides more flexibility
    - libzlib =1.2
    - zlib
    - freetype
    - libglu                         # [linux]
    - glew                           # [windows]

test:
  commands:
    - wb_command -version
    - wb_shortcuts -help

outputs:
  - name: {{ name }}-cli
    # build/host requirements should exactly match the root requirements
    requirements:
      build:
        - {{ compiler('cxx') }}
        # - {{ stdlib('c') }}
        - cmake >=3.0  # [linux]
        - cmake >=3.5  # [osx]
        - ninja
        - qwt
        # OpenMP
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        # libGL
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libxdamage') }}        # [linux]
        - {{ cdt('libxxf86vm') }}        # [linux]
        - {{ cdt('libxext') }}           # [linux]
      host:
        - qt
        - openssl
        - libzlib =1.2
        - zlib
        - freetype
        - libglu                         # [linux]
        - glew                           # [windows]
      run:
        - qt-main
        - libgl                             # [linux]
        - libglu                            # [linux]
    files:
      include:
        - bin/wb_command
        - bin/wb_command.app/**
        - bin/wb_shortcuts
        - share/bash-completion/completions/*
    test:
      commands:
        - ls -R $PREFIX/bin
        - wb_command -version
        - wb_shortcuts -help
  - name: {{ name }}
    requirements:
      run:
        - {{ pin_subpackage('dev-connectome-workbench-cli', exact=True) }}
    test:
      commands:
        - wb_command -version
        - wb_shortcuts -help

about:
  home: https://www.humanconnectome.org/software/connectome-workbench
  summary: 'Neuroimaging utility for the Human Connectome Project'
  description: |
    Connectome Workbench is an open source, freely available visualization and discovery
    tool used to map neuroimaging data, especially data generated by the Human
    Connectome Project.
  license: GPL-2.0-only
  license_family: GPL
  license_file:
    - LICENSE
    - src/CZIlib/LICENSE
    - src/QxtCore/LICENSE_qxt
    - src/kloewe/cpuinfo/LICENSE
    - src/kloewe/dot/LICENSE
  doc_url: https://humanconnectome.org/software/workbench-command
  dev_url: https://github.com/Washington-University/workbench

extra:
  recipe-maintainers:
    - Dhananjhay

```

The command I run to build the package is `CONDA_SUBDIR=osx-64 conda mambabuild . -c conda-forge --no-test` inside the `recipes/workbench` dir on the terminal.

Build Output:

During the build, I can see the executables being installed correctly:
```
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: $PREFIX/bin/wb_view.app
-- Installing: $PREFIX/bin/wb_view.app/Contents
-- Installing: $PREFIX/bin/wb_view.app/Contents/MacOS
-- Installing: $PREFIX/bin/wb_view.app/Contents/MacOS/wb_view
-- Installing: $PREFIX/bin/wb_view.app/Contents/Resources
-- Installing: $PREFIX/bin/wb_view.app/Contents/Resources/data_file.icns
-- Installing: $PREFIX/bin/wb_view.app/Contents/Resources/wb_view.icns
-- Installing: $PREFIX/bin/wb_view.app/Contents/Resources/spec_file.icns
-- Installing: $PREFIX/bin/wb_view.app/Contents/Resources/workbench.icns
-- Installing: $PREFIX/bin/wb_view.app/Contents/Info.plist
-- Installing: $PREFIX/bin/wb_command.app
-- Installing: $PREFIX/bin/wb_command.app/Contents
-- Installing: $PREFIX/bin/wb_command.app/Contents/MacOS
-- Installing: $PREFIX/bin/wb_command.app/Contents/MacOS/wb_command
-- Installing: $PREFIX/bin/wb_command.app/Contents/Info.plist
-- Installing: $PREFIX/bin/wb_shortcuts
-- Installing: $PREFIX/share/bash-completion/completions/wb_command
-- Installing: $PREFIX/share/bash-completion/completions/wb_shortcuts
```

But after the build, when I inspect the .tar.bz2 output in conda-bld/osx-64/, I only see include and info directories—no bin directory or executables.

Questions:
- Why aren’t the expected executables (wb_command, wb_shortcuts) being packaged into the final .tar.bz2?
- Am I missing something in the files: directive under outputs?
- Is there a conda-forge-compatible way to ensure that .app/Contents/MacOS/... binaries are symlinked or copied to $PREFIX/bin/ for CLI access?

Any insights would be greatly appreciated. Thanks!
